"""updates model to include colors and number of moons

Revision ID: 918c8b56b820
Revises: 30a130a4f922
Create Date: 2024-10-30 15:50:54.693236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918c8b56b820'
down_revision = '30a130a4f922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_moons', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('number_moons')

    # ### end Alembic commands ###
